YayOrNay/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using YayOrNay.Models;

namespace YayOrNay.Controllers
{//test
    public class MovieController : Controller
    {
        private YayOrNayDb db = new YayOrNayDb();

        // GET: Movie
        public ActionResult Index()
        {
            return View(db.Movies.ToList());
        }

        // GET: Movie/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // LINQ query that fetches the movies from the database to bring back releated files.
            Movie movie  = db.Movies.Include(s => s.Files).SingleOrDefault(s => s.Id == id);
            if (movie == null)
            {

                return HttpNotFound();
            }
            return View(movie);
        }

        // GET: Movie/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movie/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Genre,Certificate,ReleaseDate")] Movie movie, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {


                //upload image in controller 
                if (upload != null && upload.ContentLength > 0)
                {
                    var avatar = new File
                    {
                        FileName = System.IO.Path.GetFileName(upload.FileName),
                        FileType = FileType.Avatar,
                        ContentType = upload.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        avatar.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    movie.Files = new List<File> { avatar };
                    db.Files.Add(avatar);
                    db.Movies.Add(movie);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Create");
            }

            return View(movie);
        }

        // GET: Movie/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movie/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Genre,Certificate,ReleaseDate")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        // GET: Movie/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

YayOrNay/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YayOrNay.Models;

namespace YayOrNay.Controllers
{
    public class ReviewsController : Controller
    {
        YayOrNayDb _db = new YayOrNayDb();

        // GET: Reviews
        public ActionResult Index([Bind(Prefix = "id")]int movieId)
        {
            var movie = _db.Movies.Find(movieId);
            if(movie !=null)
            {
                return View(movie);
            }
            return HttpNotFound();

        }

        [HttpGet]
        public ActionResult Create (int movieId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(MovieReview review)
        {
           if(ModelState.IsValid)
           {
               _db.Reviews.Add(review);
                // get current movie from Movies list in db
                Movie movie = _db.Movies.Find(review.MovieId);
                // get the list of review in cerrent movie
                ICollection<MovieReview> reviews = movie.Reviews;
                // add new review into the review list
                reviews.Add(review);
               _db.SaveChanges();
               return RedirectToAction("Index", new { id = review.MovieId });
           }
           return View(review);
        }

        [HttpGet]
        public ActionResult Edit (int id)
        {
            var model = _db.Reviews.Find(id);
            return View(model);
        }

        //[Bind(Exclude = "ReviewerName")]
        [HttpPost]
        public ActionResult Edit (MovieReview review)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(review).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index", new { id = review.MovieId });
            }
            return View(review);
        }



        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
            base.Dispose(disposing);
        }   

    }
}

YayOrNay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
  
    <meta name="viewport" content="width=device-width" /> 

    @Styles.Render("~/Content/themes/base/css")


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")



</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

              

                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Movies", "Index", "Movie")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>



    @*This part was suppose to help the async for pagForce ing but it does not work for some reason*@

    <div class="container body-content ">
       
       
            @RenderBody()
       
    </div> 



           @*<div>
            @Html.Action("BestReview", "Reviews")
           </div>*@



        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
   

    @Scripts.Render("~/bundles/yon")

    @*@Scripts.Render("~/bundles/bootstrap")*@

    @RenderSection("scripts", required: false)
</body>
</html>

YayOrNay/Views/Shared/_Review.cshtml
@model YayOrNay.Models.MovieReview

<div class="review">
    <h4>@Model.Title</h4>
    <p>Rating @Model.Rating /10</p>
    <p>@Model.Genre</p>
    <p>@Model.Certificate</p>
    <p>@Model.ReleaseDate</p>

    <span class="right ">
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
    </span>
</div>